export default {
  baseUrl: "",
  name: "PONO",
  PROTOCOLS: ["http:", "https:", "mqtt:", "mqtts:", "ws:", "wss:", "fluent:"],

  BASE_FETCH:    "BASE_FETCH",

  USER_SIGNIN:  "USER_SIGNIN",
  USER_SIGNUP:  "USER_SIGNUP",
  USER_SIGNOUT: "USER_SIGNOUT",
  USER_CURRENT: "USER_CURRENT",

  RULE_CREATE:   "RULE_CREATE",
  RULE_FETCHALL: "RULE_FETCHALL",
  RULE_FETCH:    "RULE_FETCH",
  RULE_MODIFY:   "RULE_MODIFY",
  RULE_DELETE:   "RULE_DELETE",

  TOKEN_CREATE:   "TOKEN_CREATE",
  TOKEN_FETCHALL: "TOKEN_FETCHALL",
  TOKEN_FETCH:    "TOKEN_FETCH",
  TOKEN_MODIFY:   "TOKEN_MODIFY",
  TOKEN_DELETE:   "TOKEN_DELETE",

  PROP_CREATE:   "PROP_CREATE",
  PROP_FETCHALL: "PROP_FETCHALL",
  PROP_FETCH:    "PROP_FETCH",
  PROP_MODIFY:   "PROP_MODIFY",
  PROP_DELETE:   "PROP_DELETE",

  ERROR:         "ERROR"
};
